server:
  port: 8020
feign:
 hystrix:
  enabled: true
ribbon:
  eureka:
    enable: true
    isSecure: false
    readTimeout: 60000
    connectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
